\import first
{-Exercise 1: Implement the function lookup, which takes a list xs and a natural number n
and returns the n-th element in the list. The function should also take a proof that n is in the right range:
 T (n < length xs).-}
\func reverse {A : \Type} (xs : List A) : List A => rev nil xs
  \where
    \func rev {A : \Type} (acc xs : List A) : List A \elim xs
      | nil => acc
      | cons x xs => rev (cons x acc) xs
